### ISSUE TITLE
Crash on launch for JATV 12.4 via twitch client

### ISSUE THREAD

**Issue by arronhuk** [BedrockLegends/Journey-Across-The-Void#9]
Issue description:
Everytime I try to launch version 12.4 (even on a new profile) from the twitch launcher it crashes with the error

11:00:06.615
Portal Gun Fixer
main
Fixing classpath order
11:00:06.657
Portal Gun Fixer
main
Loading external classpath entry iChunUtil-1.12.2-7.1.4.jar
11:00:06.742
Portal Gun Fixer
main
Loading external classpath entry PortalGun-1.12.2-7.1.0.jar
11:00:06.756
Portal Gun Fixer
main
Initializing Mixin
11:00:06.826
LaunchWrapper
main
Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\arron\Documents\Curse\Minecraft\Instances\Journey Across The Void (1) for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42)
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
	at de.kitsunealex.portalfixer.PGFLoadingPlugin.<clinit>(PGFLoadingPlugin.java:32)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527)
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451)
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107)
	... 5 more
11:00:06.833
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
11:00:06.833
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
11:00:06.833
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
11:00:06.833
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
11:00:06.834
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
11:00:06.834
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
11:00:06.834
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 

 
Steps to reproduce:
1.choose profile
2.click play
3.click launch on minecraft screen 

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):

Forge Version:forge-14.23.5.2854

Server Version:

Modpack Version:12.4

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 https://pastebin.com/6YSvMrKQ

PC: 32GB ram (12GB allocated to minecraft), 1920x CPU, GTX 1070 GPU

**Comment by MasterSloth1** [comment]
go into your mods folder and remove these 2 mods 
PortalGunFixer-0.0.2.jar
PortalGunFixer-0.0.2.jar.disabled

**Comment by arronhuk** [comment]
thanks, that worked like a dream
